config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "services#index"
  resources :users, only: %i[show]
  resources :services do
    resources :bookings, only: %i[new create]
  end

  # resources :bookings
  get "/my_bookings/:id", to: "bookings#my_bookings", as: :my_bookings
  get "/my_services/:id", to: "services#my_services", as: :my_services
  get "/my_requests/:id", to: "bookings#my_requests", as: :my_requests
  get "/my_requests/:id/confirm", to: "bookings#confirm", as: :confirm_request
  get "/profile", to: "users#profile", as: :profile
  # get "/user/edit", to: "users#edit", as: :edit_user
  # patch  "/user", to: "users#update"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/categories", to: "services#categories", as: :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :service

  # validates_associated :user, :service

  validates :starting_date, :end_date, presence: true

end

app/models/service.rb
class Service < ApplicationRecord
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  belongs_to :user
  # validates_associated :user
  validates :description, :title, :price, presence: true
  CATEGORY = %w[Pets Cleaning Babysitting Gardening Cooking Admin Car Locksmith DIY Tutoring Events Other]
  validates :category, presence: true, inclusion: { in: CATEGORY }
  # validates_uniqueness_of :user_id, scope: [:service_id]
  include PgSearch::Model
  pg_search_scope :search_by_title_and_etc,
  against: [ :title, :description, :category],
  associated_against: {
    user: %i[first_name last_name username]
  },
  using: {
    tsearch: { prefix: true }
  }

  pg_search_scope :search_by_name,
  against: [:description],
  associated_against: {
    user: %i[first_name last_name username]
  },
  using: {
    tsearch: { prefix: true }
  }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :services

  has_many :bookings
  has_one_attached :photo

  validates :username, :first_name, :last_name, :location, :password, presence: true
  validates :username, uniqueness: { case_sensitive: false }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name location username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name location username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show destroy]
  before_action :set_service, only: [:new, :create]

  def index
    @bookings = Booking.all
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.service = @service
    @booking.user = current_user
    if @booking.save
      redirect_to my_bookings_path(@booking)
    else
      render :new
    end
  end

  def my_bookings
    @bookings = Booking.all
    @user = current_user
    # @bookings = Booking.where(user: current_user)
  end

  def my_requests
    @bookings = Booking.all
    @user = current_user
    # @bookings = Booking.where(user: current_user)
  end

  def destroy
    @booking.destroy
    redirect_to services_path(@booking.service), status: :see_other
  end

  private

  def booking_params
    params.required(:booking).permit(:starting_date, :end_date, :service_id, :user_id)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_service
    @service = Service.find(params[:service_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @service = Service.find(params[:service_id])
    @user = current_user
    @review.service = @service
    if @review.save
      redirect_to service_path(@service)
    else
      render 'services/show', status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to service_path(@review.service)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index


  def index
    if params[:query].present?
      @services = Service.search_by_title_and_etc(params[:query])
      categories = @services.pluck(:category).uniq
      @services = []
      categories.each do |category|
        @services << Service.find_by(category: category)
      end
    else
      @services = Service.all
      categories = @services.pluck(:category).uniq
      @services = []
      categories.each do |category|
        @services << Service.find_by(category: category)
      end
    end
  end

  def show
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.user = current_user

    if @service.save
      redirect_to my_services_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def my_services
    @services = Service.all
    @user = current_user
  end

  def edit
  end

  def update
    @service.update(service_params)
    redirect_to service_path(@service)
  end

  def destroy
    @service.destroy
    redirect_to my_services_path, status: :see_other
  end

  def categories
    if params[:query].present?
      @services = Service.search_by_title_and_etc("#{params[:query]} #{params[:category]}")
    else
      @services = Service.where(category: params[:category])
    end
  end

  private

  def service_params
    params.required(:service).permit(:title, :description, :category, :price, :photo)
  end

  def set_service
    @service = Service.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  def profile
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to profile_path(@user)
  end


  private

  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :location, :email, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
  <div class="card card-body w-50">

      <%= simple_form_for [@service, @booking] do |f| %>
      <%= f.input :starting_date, as: :date, html5: true %>
      <%= f.input :end_date, as: :date, html5: true %>
      <%= f.hidden_field :service_id, value: @service.id %>
      <%= f.hidden_field :user_id , value: @booking.user_id %>

      <br>
        <%= f.submit %>
      <% end %>
      <br>

  </div>

app/views/bookings/my_bookings.html.erb
<div class="container">
<h1>MY BOOKINGS</h1>
<% @bookings.each do |booking|%>
      <% if booking.user_id == @user.id %>
        <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
          <div class="bg-white rounded shadow h-100">
            <div class="p-3 rounded-bottom d-flex flex-column">
              <strong><%= booking.service.title %><br>
              <small class="text-muted">Start date: <%= booking.starting_date %></small><br>
              <small class="text-muted">End date: <%= booking.end_date %></small><br>
               <% if booking.pending == true %>
              <small class="text-muted">Status: pending </small><br>
               <% end %>
                <% if booking.confirmed == true %>
              <small class="text-muted">Confirmed?  Yes! </small><br>
              <% else %>
               <small class="text-muted">Confirmed?  Not yet</small><br>
               <% end %>

              <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
               <%= link_to user_path(booking.service.user), class:"text-decoration-none" do %>
               <i class="fa-solid fa-user"></i><small class="flex-grow-1">  <%=  booking.service.user.username %></small>
               <% end %>
              </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
  </div>
  <hr class="my-5">

</div>

app/views/bookings/my_requests.html.erb
<div class="container">
<h1>MY BOOKING REQUESTS</h1>
<% @bookings.each do |booking|%>
      <% if booking.service.user_id == @user.id %>
        <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
          <div class="bg-white rounded shadow h-100">
            <div class="p-3 rounded-bottom d-flex flex-column">
              <strong><%= booking.service.title %><br>
              <small class="text-muted">Start date: <%= booking.starting_date %></small><br>
              <small class="text-muted">End date: <%= booking.end_date %></small><br>
               <% if booking.pending == true %>
              <small class="text-muted">Status: pending </small><br>
               <% end %>
                <% if booking.confirmed == true %>
              <small class="text-muted">Confirmed?  Yes! </small><br>
              <% else %>
               <small class="text-muted">Confirmed?  Not yet</small><br>
               <% end %>
              <small class="text-muted"><%= button_to "confirm", "#", method: :get %></small><br>
              <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <%= link_to user_path(booking.service.user), class:"text-decoration-none" do %>
                  <i class="fa-solid fa-user"></i><small class="flex-grow-1">  <%=  booking.service.user.username %></small>
                 <% end %>
                <small class="text-muted">Name:   <%= booking.user.first_name.capitalize %> <%= booking.user.last_name.capitalize %></small><br>
              </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
  </div>
  <hr class="my-5">

</div>

app/views/bookings/new.html.erb
<div class="container">
<br>
<h1>New Booking</h1>

<%= render "form", booking: @booking  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>GetAHand</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="wrapper">
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="content-container">
      <%= yield %>
    </div>
    <div class="push"></div>
  </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
<br>
<div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
 <div class="bg-white rounded shadow h-100">
 <div class="p-3 rounded-bottom d-flex flex-column">
<strong><h1>Get help with any issue</h1></strong>
<strong><h1>Earn money by helping out</h1></strong>
</div>
</div>
</div>

<h4>Join our community and get help when and where you need it</h4>



<%= link_to "Browse Services", services_path, class: "btn btn-primary text-decoration-none" %>
</div>

app/views/services/_form.html.erb
<div class="card card-body w-50">


<%= simple_form_for service do |f| %>
  <%= f.input :title %><br><br>
  <%= f.input :description %><br><br>
  <%= f.input :category, collection: Service::CATEGORY  %><br><br>
  <%= f.input :price %><br><br>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

</div>

app/views/services/categories.html.erb
<div class="category-banner", style="background-image: url('<%=cl_image_path @services.first.photo.key%>')">
  <section style="">
    <div class="container py-5">
    <div class="sticky-search">
      <%= form_with url: categories_path, method: :get, id:"search-bar", class: "d-flex" do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find User/Title/Description"
         %>
         <%= hidden_field_tag :category,
        params[:category],
        class: "form-control",
        placeholder: "Find User/Title/Description"
         %>
        <%= submit_tag "🔎", class: "btn-search" %>
      <% end %>
    </div>
  </div>
</div>
 <div class="container py-5">
    <div class="row row-cols-3 mt-3 gy-4">

      <% @services.each do |service| %>
      <div class="col-12 col-sm-6 col-lg-4">
        <div class="card shadow h-100" style="border-radius: 15px;">
          <div class="bg-image hover-overlay ripple ripple-surface ripple-surface-light p-3 rounded-bottom d-flex flex-column"
            data-mdb-ripple-color="light">
            <% if service.user.photo.attached?%>
            <%= image_tag  cl_image_path service.user.photo.key, height: 400, crop: :fill, style:"border-top-left-radius: 15px; border-top-right-radius: 15px;", class:"img-fluid"%><br>
            <% else %>
            <%= image_tag asset_path('lukas.jpg'),height: 400, crop: :fill, style:"border-top-left-radius: 15px; border-top-right-radius: 15px;", class:"img-fluid"%><br>
            <% end %>
              <div class="mask"></div>
            </a>
          </div>
          <div class="card-body pb-0">
            <div class="d-flex justify-content-between">
              <div>
                <p><a href="#!" class="text-dark"><%= service.title %></a></p>
                <p class="small text-muted"><%= service.category %></p>
              </div>
              <div>
                <div class="d-flex flex-row justify-content-end mt-1 mb-4 text-danger">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                </div>
                <p class="text-dark"><%= service.price %> <i class="fas fa-euro-sign"></i></p>
              </div>
            </div>
          </div>

          <div class="card-body pb-0">
            <div class="d-flex justify-content-between">
              <%= service.description %>
            </div><br>
          </div>
          <hr class="my-0" />
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-center pb-2 mb-1">
            <%= link_to user_path(service.user), class:"text-decoration-none" do %>
                 <i class="fa-solid fa-user"></i><small class="flex-grow-1">  <%=  service.user.username %></small>
               <% end %>
               <p><%= link_to "Book", new_service_booking_path(service), class: "btn btn-primary text-decoration-none"  %></p>
            </div>
          </div>
        </div>
      </div>
      <% end %>

    </div>
    </div>
  </div>
</section>

app/views/services/edit.html.erb
<%= simple_form_for @service do |f| %>
<%= f.input :category %>
<%= f.input :description %>
<%= f.input :title %>
<%= f.input :price %>
<%= f.submit "Submit Edit", class: "btn-btn-primary" %>
<% end %>

app/views/services/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://res.cloudinary.com/dl7iiaefg/image/upload/v1669115006/development/te6kwicoxz1oap5haqma.jpg');">
  <div class="container">
    <h1 class="text-center">Get-a-hand</h1>
    <h1 class="text-center">Choose any kind of service</h1>
    <p class="text-center">Start now!</p>
      <%= form_with url: services_path, method: :get, id:"search-bar", class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
      class: "form-control",
      placeholder: "Find a category"
       %>
      <%= submit_tag "🔎", class: "btn-search" %>
      <% end %>
  </div>

</div>

<div class="container mt-5">
  <div class="d-flex justify-content-between">
    <h4 id="title">Top categories</h4>
  </div>

   <div class="row row-cols-3 mt-3 gy-4"  >
    <% @services.each do |service| %>
      <%=link_to categories_path(category: service.category), class: "text-decoration-none" do %>

          <div class="col">
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),url(<%= service.photo.attached? ?  service.photo.url : 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3387&q=80' %>);">

              <p class=" link-light "><%= service.category %></p>

            </div>
          </div>

      <% end %>
    <% end %>

  </div>


<script>

// document.getElementById("search-bar").remove()r")
  // const title = document.getElementById("title")
//
  // const search = () => {
    // let searchBar = document.getElementById("search-bar")
    // let searchQuery = document.getElementById("query")
    // console.log("hello")
    // searchQuery.value="babysitting"
    // searchBar.submit()
  // }
//
  // title.addEventListener("click", search)
//
//
</script>

app/views/services/my_services.html.erb
<div class="container">
<br>
<h1>MY SERVICES</h1>
<br>
    <% @services.each do |service|%>
      <% if service.user_id == @user.id %>
        <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
          <div class="bg-white rounded shadow h-100">
            <div class="p-3 rounded-bottom d-flex flex-column">
              <strong><%= service.title %> <span class="text-muted font-weight-normal">• <%= service.price %> <i class="fas fa-euro-sign"></i></span></strong>
              <small class="text-muted"><%= service.description %></small>
              <div class="d-flex align-items-end justify-content-between pt-4">
              <%= link_to "delete", service_path(service), class: "btn btn-cancel", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this service" } %>
              <%= link_to "edit", edit_service_path(service), class: "btn btn-cancel" %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
  </div>
  <hr class="my-5">

app/views/services/new.html.erb
<!-- Pills navs -->

<section class="vh-200" style="background-color: #bdd2b6;">
<div class="container py-5 h-100">
  <div class="row d-flex justify-content-center align-items-center h-100">
   <div class="col-12 col-md-8 col-lg-6 col-xl-5">
  <div class="card shadow-2-strong" style="border-radius: 1rem;">
  <div class="card-body p-5 text-center">

<!-- Pills navs -->

<!-- Pills content -->
<div class="tab-content">
  <div class="tab-pane fade show active" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
      <!-- Email input -->
      <%= simple_form_for @service do |f| %>
  <%= f.input :title %><br><br>
  <%= f.input :description %><br><br>
  <%= f.input :category, collection: Service::CATEGORY  %><br><br>
  <%= f.input :price %><br><br>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>
      <!-- Register buttons -->

  </div>
  </div>
</div>
</div>
</section>

app/views/services/show.html.erb
<section style="background-color: #eee;">
<% users = User.all %>
    <% users.each do |user| %>
    <% if user.id == @service.user_id %>
       <% @user = user %>
        <% end %>
    <% end %>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
        <div class="card shadow h-100" style="border-radius: 15px;">
          <div class="bg-image hover-overlay ripple ripple-surface ripple-surface-light p-3 rounded-bottom d-flex flex-column"
            data-mdb-ripple-color="light">
            <% if @service.photo.attached?%>
            <%= image_tag  cl_image_path @service.photo.key, height: 400, crop: :fill, style:"border-top-left-radius: 15px; border-top-right-radius: 15px;", class:"img-fluid"%><br>
            <% end %>
              <div class="mask"></div>
            </a>
          </div>
          <div class="card-body pb-0">
            <div class="d-flex justify-content-between">
              <div>
                <p><a href="#!" class="text-dark"><%= @service.title %></a></p>
                <p class="small text-muted"><%= @service.category %></p>
              </div>
              <div>
                <div class="d-flex flex-row justify-content-end mt-1 mb-4 text-danger">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                </div>
                <p class="text-dark"><%= @service.price %> <i class="fas fa-euro-sign"></i></p>
              </div>
            </div>
          </div>

          <div class="card-body pb-0">
            <div class="d-flex justify-content-between">
              <%= @service.description %>
            </div><br>
          </div>
          <hr class="my-0" />
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-center pb-2 mb-1">
            <%= link_to user_path(@user), class:"text-decoration-none" do %>
                 <i class="fa-solid fa-user"></i><small class="flex-grow-1">  <%=  @user.username %></small>
               <% end %>
               <p><%= link_to "Book", new_service_booking_path(@service), class: "btn btn-primary text-decoration-none"  %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This Website was made to make your life easier
    <%# <i class="fas fa-heart"></i> at Le Wagon %>
  </div>
  <div>
    Home | Info | Contact
  </div>
</div>

app/views/shared/_navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand my-image" do %>
      <%= image_tag asset_path('hand-logo-5.png') %>
      <%= "Get-A-Hand" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Services", services_path, class: "nav-link" %>
              </li> <li>
                <%= link_to "My Bookings", my_bookings_path(current_user), class: "nav-link" %>
            </li>

          <li class="nav-item dropdown">
          <% @user = current_user%>
          <% if @user.photo.attached?%>

          <%= image_tag asset_path(cl_image_path @user.photo.key), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %><br>

          <% else %>
          <%= image_tag asset_path('profile.png'), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %><br>
          <% end %>
           <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path(current_user), class: "dropdown-item" %>
              <%= link_to "New Service", new_service_path, class: "dropdown-item" %>
              <%= link_to "My Services", my_services_path(current_user), class: "dropdown-item" %>
              <%= link_to "My Requests", my_requests_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<section class="h-100 gradient-custom-2">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card">
          <div class="rounded-top text-white d-flex flex-row" style="background-color: #395144; height:200px;">
            <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
            <% if @user.photo.attached?%>
              <%= image_tag asset_path(cl_image_path @user.photo.key), class:"img-fluid img-thumbnail mt-4 mb-2",
                style:"width: 150px; z-index: 1"%><br>

            <% else %>
              <%= image_tag asset_path('lukas.jpg'), class:"img-fluid img-thumbnail mt-4 mb-2",
                style:"width: 150px; z-index: 1"%>
            <% end %>
            </div>
            <div class="ms-3" style="margin-top: 80px;">
              <h5><%= @user.first_name.capitalize%> <%= @user.last_name.capitalize%></h5>
              <p><%= @user.location%></p>
            </div>
          </div>
          <div class="p-4 text-black" style="background-color: #BDD2B6;">
            <div class="d-flex justify-content-end text-center py-1">
              <div class="px-3">
                <p class="mb-1 h5">1026</p>
                <p class="small text-muted mb-0">Followers</p>
              </div>
              <div>
                <p class="mb-1 h5">478</p>
                <p class="small text-muted mb-0">Following</p>
              </div>
            </div>
          </div>
          <div class="card-body p-4 text-black" style="background-color: #BDD2B6;">
            <div class="mb-5">
              <p class="lead fw-normal mb-1">Account Details</p>
              <div class="p-4" style="background-color: #f8f9fa;">
                <p class="font-italic mb-1">Email: <%= @user.email%> </p></p>
                <p class="font-italic mb-1">Username: <%= @user.username%></p></p>
              </div>
            </div>
            <div class="card-body p-4 text-black">
            <div class="mb-5">
              <p class="lead fw-normal mb-1">About</p>
              <div class="p-4" style="background-color: #f8f9fa;">
                <p class="font-italic mb-1">Hi, I'm Ben, I like to help out and I'm very versatile. Locksmithing is more of a hobby since my true passion is babysitting. I guess you could say I'm a full time baby lover!</p></p>
              </div>
            </div>
            </div>
          </div>
           <%=link_to "Edit profile", edit_user_registration_path(@user), class:"btn btn-outline-dark"%>
        </div>
      </div>
    </div>
  </div>
</section>